apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT}
  labels:
    app: ${APP}
    app.kubernetes.io/managed-by: cloud-console
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: ${APP}
      app.kubernetes.io/managed-by: cloud-console
  template:
    metadata:
      labels:
        app: ${APP}
        app.kubernetes.io/managed-by: cloud-console
    spec:
      containers:
        - name: ${CONTAINER}
          image: ${IMAGE}
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE}
spec:
  selector:
    app: ${APP}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
